///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class ContactModels {


  bool? status;
  String? message;
  ContactData? data;


  ContactModels.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? ContactData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ContactData {


  int? currentPage;
  List<ContactDataData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;


  ContactData.fromJson(Map<String, dynamic> json) {
    currentPage = json['current_page']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ContactDataData>[];
      v.forEach((v) {
        arr0.add(ContactDataData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json['first_page_url']?.toString();
    from = json['from']?.toInt();
    lastPage = json['last_page']?.toInt();
    lastPageUrl = json['last_page_url']?.toString();
    nextPageUrl = json['next_page_url']?.toString();
    path = json['path']?.toString();
    perPage = json['per_page']?.toInt();
    prevPageUrl = json['prev_page_url']?.toString();
    to = json['to']?.toInt();
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['current_page'] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['first_page_url'] = firstPageUrl;
    data['from'] = from;
    data['last_page'] = lastPage;
    data['last_page_url'] = lastPageUrl;
    data['next_page_url'] = nextPageUrl;
    data['path'] = path;
    data['per_page'] = perPage;
    data['prev_page_url'] = prevPageUrl;
    data['to'] = to;
    data['total'] = total;
    return data;
  }
}

class ContactDataData {


  int? id;
  int? type;
  String? value;
  String? image;
  String? nameTag;


  ContactDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    type = json['type']?.toInt();
    value = json['value']?.toString();
    image = json['image']?.toString();
    nameTag = Tag[id!];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['type'] = type;
    data['value'] = value;
    data['image'] = image;
    return data;
  }

  Map< int, String> Tag = {
    1:'Facebook',
    2:'Instagram',
    3:'Twitter',
    4:'Email',
    5:'Phone',
    6:'Whatsapp',
    7:'Snapchat',
    8:'Youtube',
    9:'Website',
  };
}




